package pkg

const (
	IPC_ENABLED   = "IPC_ENABLED"
	IPC_ENDPOINT  = "IPC_ENDPOINT"
	HTTP_ENABLED  = "HTTP_ENABLED"
	HTTP_ENDPOINT = "HTTP_ENDPOINT"

	LEVELDB_PATH         = "LEVELDB_PATH"
	LEVELDB_CACHE_SIZE   = "LEVELDB_CACHE_SIZE"
	LEVELDB_HANDLER_NUM  = "LEVELDB_HANDLER_NUM"
	LEVELDB_FREEZER_PATH = "LEVELDB_FREEZER_PATH"
	LEVELDB_NAMESPACE    = "LEVELDB_NAMESPACE"
	LEVELDB_READ_ONLY    = "LEVELDB_READ_ONLY"
)
